CREATE SCHEMA nanoymovie;
USE nanoymovie;

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";



CREATE TABLE `film` (
  `id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `genre` varchar(255) NOT NULL,
  `image` varchar(255) NOT NULL,
  `description` text NOT NULL,
  `release_date` date NOT NULL,
  `age_rating` varchar(11) NOT NULL,
  `movie_rating` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


INSERT INTO `film` (`id`, `title`, `genre`, `image`, `description`, `release_date`, `age_rating`, `movie_rating`) VALUES
(121, 'Star Wars : The Last Jedi', '3', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/ySaaKHOLAQU5HoZqWmzDIj1VvZ1.jpg', 'Film ini mengisahkan Rey (Daisy Ridley) akhirnya berhasil menemukan ksatria legendaris Jedi, Luke Skywalker (Mark Hamill) di sebuah pulau dengan aura magis. Para pahlawan dari The Force Awakens diantaranya Leia, Finn dan Poe bergabung dengan sang legenda dalam sebuah petualangan epik, yang membuka misteri kuno The Force dimasa lalu yang mengejutkan.', '2017-12-13', '13+', 9),
(122, 'Doctor Strange In The Multiverse Of Madness', '7', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/hq2igFqb31fDqGotz8ZuUfwKgn8.jpg', 'Film ini menggambarkan Perjalanan ke tempat yang tidak diketahui bersama Doctor Strange, dengan bantuan sekutu mistis baik lama maupun baru, melintasi realitas alternatif Multiverse yang membingungkan dan berbahaya untuk menghadapi musuh baru yang misterius.', '2022-05-05', '13+', 9),
(123, 'Spider-Man: No Way Home', '7', 'https://img.okezone.com/okz/500/library/images/2021/11/30/w9mqgij6wjg80xu1sppe_18358.jpg', 'Identitas Spider-Man sekarang sudah terungkap, dan Peter meminta bantuan Doctor Strange. namun sebuah kesalahan terjadi, dan itu justru mengundang musuh berbahaya dari dunia lain, mereka mulai bermunculan. Hal itu memaksa Peter mencari apa makna sebenarnya menjadi Spider-Man..', '2021-12-15', '13+', 8),
(124, 'Eternals', '3', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/bcCBq9N1EMo3daNIjWJ8kYvrQm6.jpg', 'Marvel Studios meluncurkan Eternals yakni menghadirkan kisah sekelompok pahlawan dari luar angkasa yang telah melindungi Bumi sejak awal peradaban manusia.', '2021-11-03', '17+', 5),
(125, 'Jurassic World Dominion', '7', 'https://www.universalpictures.co.uk/tl_files/content/movies/jurassic_world_dominion/poster/02.jpg', 'Empat tahun setelah kehancuran pulau Nublar, dinosaurus sekarang hidup dan berburu bersama manusia di seluruh dunia. Keseimbangan yang rapuh ini akan menentukan, apakah manusia akan tetap menjadi berada di puncak rantai makanan ketika berbagi wilayah dengan makhluk paling menakutkan dalam sejarah bumi.', '2022-06-07', '13+', 8),
(126, 'Shang-Chi and the Legend of the Ten Rings', '3', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/1BIoJGKbXjdFDAqUEiA2VHqkK1Z.jpg', 'SShang-Chi (Simu Liu) harus menghadapi masa lalunya sebelum ia memilih untuk meninggalkan dan bergabung ke dalam sebuah organisasi bernama Ten Rings.', '2021-12-30', '13+', 8),
(127, 'The Boss Baby: Family Business', '4', 'https://m.media-amazon.com/images/M/MV5BZmQ0YTUxN2MtNDAxYy00NmE4LTk2YmQtYTJlZmFjYThhYmU2XkEyXkFqcGdeQXVyMTA3MDk2NDg2._V1_.jpg', 'Saudara-saudara Templeton telah menjadi dewasa dan menjauh satu sama lain, tetapi kehadiran Boss Baby baru dengan sesuatu mutakhir akan menyatukan mereka lagi dan juga menginspirasi bisnis keluarga baru.', '2021-07-02', 'SU', 7),
(128, 'Tom & Jerry', '4', 'https://m.media-amazon.com/images/M/MV5BNTgwMjRlMDItMGIyNi00ZjJiLWEzNzgtZjI3OGRmZWU4YTUzXkEyXkFqcGdeQXVyMTA3MDk2NDg2._V1_.jpg', 'Salah satu persaingan paling dicintai dalam sejarah muncul kembali ketika Jerry pindah ke hotel terbaik di New York City pada malam "pernikahan abad ini", memaksa perencana acara yang putus asa untuk mempekerjakan Tom untuk menyingkirkannya. Pertarungan kucing dan tikus yang terjadi selanjutnya mengancam untuk menghancurkan karirnya, pernikahan dan mungkin hotel itu sendiri. Tapi segera, masalah yang lebih besar muncul: seorang staf yang sangat ambisius berkonspirasi melawan mereka bertiga.', '2021-03-10', 'SU', 8),
(129, 'Sing 2', '4', 'https://m.media-amazon.com/images/M/MV5BMTYxNjE5ZGYtNmIwMS00ZWZlLWE3YzgtZWM4NzEyYzU2ZTdmXkEyXkFqcGdeQXVyMTA3MDk2NDg2._V1_.jpg', 'Petualangan Buster Moon dan teman-temannya kembali, kali ini mereka harus membujuk bintang rock Clay Calloway untuk bergabung dengan mereka untuk sebuah pembukaan pertunjukan baru.', '2022-01-07', 'SU', 6),
(130, 'Uncharted', '3', 'https://m.media-amazon.com/images/M/MV5BMWEwNjhkYzYtNjgzYy00YTY2LThjYWYtYzViMGJkZTI4Y2MyXkEyXkFqcGdeQXVyNTM0OTY1OQ@@._V1_FMjpg_UX1000_.jpg', 'menceritakan tentang aksi perburuan harta karun terbesar yang tidak pernah ditemukan. Nathan Drake merupakan seorang bartender yang pintar. Nathan mengaku bahwa dirinya adalah keturunan dari penjelajah kenamaan asal Inggris bernama Sir Francis Drake.', '2022-02-16', '17+', 7),
(131, 'Red Notice', '7', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/lAXONuqg41NwUMuzMiFvicDET9Y.jpg', 'Demi menangkap penjahat licin yang selalu selangkah di depan, penganalisis FBI terpaksa bersekutu dengan pencuri karya seni paling dicari yang selama ini dikejarnya.', '2021-11-05', '17+', 5),
(132, 'Bubble', '4', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/mIeQQgXxPyX2VwRLMl6jsvD2KOR.jpg', 'Tokyo ditinggalkan oleh orang-orang karena dikuasai oleh gelembung dan kelainan gravitasi, seorang pemuda berbakat bertemu dengan seorang gadis misterius.', '2022-04-28', 'SU', 7),
(133, 'Dilan 1991', '8', 'https://m.media-amazon.com/images/M/MV5BYzNhNGY1YjItMDhmOS00ODc0LWI0NTYtNGM3ODdmODM1ZjdhXkEyXkFqcGdeQXVyNzEzNjU1NDg@._V1_.jpg', 'Kisah cinta Dilan dan Milea akan kembali berlanjut. Di film Dilan 1991 ini kisah cinta mereka akan mulai diuji. Banyak rintangan yang harus Dilan dan Milea lalui, mampukah cinta mereka bertahan?', '2019-02-28', '13+', 10),
(134, 'Warkop DKI Reborn: Jangkrik Boss! Part 1', '6', 'https://m.media-amazon.com/images/M/MV5BZjYwMGM0NGMtOTM4Zi00OTNhLTgwZTItNzYwMzc5YzE4ZjJhXkEyXkFqcGdeQXVyNjIwMTgzMTg@._V1_FMjpg_UX1000_.jpg', 'Film yang menghidupkan kembali legenda trio komedi Warkop. Dono, Kasino dan Indro kembali beraksi di tengah hiruk pikuknya kota DKI Jakarta. Mereka sekali lagi berperan sebagai personel sebuah Lembaga Swasta yang bernama CHIIPS (Cara Hebat Ikut-Ikutan Penanggulangan Sosial). Walaupun di dalam diri mereka dipenuhi semangat yang menggelora dalam menjalankan tugas-tugasnya melayani masyarakat, namun kekacauan dan huru-hara selalu mereka timbulkan akibat aksi mereka yang konyol dan selalu mengocok perut.', '2016-09-02','13+', 9),
(135, 'Ada Apa dengan Cinta?', '8', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/v7HMMGgWqxeIObCMouvU8mWPWCv.jpg', 'Bertemakan cinta di masa-masa SMA, Ada Apa dengan Cinta menampilkan Cinta (Dian Sastrowardoyo) sebagai seorang pelajar SMA. Ia langganan juara lomba puisi di sekolahnya yang rutin diadakan tiap tahun. Cerita berawal dari Alya (Ladya Cherill) yang tubuhnya memar karena kerap dipukuli sang ayah yang kerap cek-cok dengan ibunya. Alya adalah sahabat karib Cinta dengan teman-temannya yang lain seperti Carmen (Adinia Wirasti), Maura (Titi Kamal), dan Milly (Sissy Priscillia)', '2002-02-8', '13', 9),
(136, 'Gundala ', '7', 'https://m.media-amazon.com/images/M/MV5BMTZlNDdmNzAtZTI3Mi00ZmVkLTg3OWYtNTIxZWZmNjU1MDMyXkEyXkFqcGdeQXVyNDA1NDA2NTk@._V1_.jpg', 'Sancaka hidup di jalanan sejak ditinggal orang tuanya. Menjalani kehidupan yang keras, Sancaka bertahan dengan memikirkan keselamatannya sendiri. Ketika kondisi kota semakin buruk dan ketidakadilan mengamuk di seluruh negeri, Sancaka harus memutuskan apakah dia akan terus hidup untuk menjaga dirinya sendiri atau bangkit untuk menjadi pahlawan mereka yang tertindas.', '2019-08-29', 'SU', 7),
(137, 'Dear Nathan: Thank You Salma', '8', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/gl0eVGJW8VlwpR91AFDe2m8TO0S.jpg', 'Masa paling romantis dalam hubungan cinta NATHAN dan SALMA baru saja dimulai. Tahun ini, Nathan dan Salma mulai memasuki dunia aktivisme sosial. Sayangnya Salma dan Nathan memiliki prinsip yang berbeda. Salma cenderung memilih berekspresi secara digital sementara Nathan memilih turun ke jalan.', '2022-01-13', '13', 8),
(138, 'Jungle Cruise', '3', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/9dKCd55IuTT5QRs989m9Qlb7d2B.jpg', 'Kisah berawal dari kapten kapal bernama Frank yang berkharisma. Ia berjumpa dengan Lily, salah satu penjelajah yang sedang berpetualang menghadapi misi yakni menemukan kebenaran soal pohon yang memiliki kekuatan penyembuh segalanya. Sayangnya, ia harus segera menemukan pohon tersebut. Jika jatuh ke tangan yang salah, pohon tersebut akan dimanfaatkan untuk membangkitkan kekuatan jahat di muka bumi Frank yang awalnya tak percaya kemudian menemukan beberapa fakta soal keajaiban tersebut. Keduanya pun bersatu dalam petualangan yang menantang.', '2021-10-06', 'SU', 8),
(139, 'Stranger Things', '3', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/uKYUR8GPkKRCksczYDJb3pwZauo.jpg', 'Ketika seorang bocah lelaki menghilang, sebuah kota kecil mengungkap misteri yang melibatkan eksperimen rahasia, kekuatan gaib yang menakutkan, dan seorang gadis kecil yang aneh.', '2016-07-15', '17+', 8),
(140, 'Perempuan Tanah Jahanam', '5', 'https://m.media-amazon.com/images/M/MV5BMmE2MmM5Y2YtNzEzMy00ZjJiLWE2ZWEtYzMzZGYxMTYxNDM2XkEyXkFqcGdeQXVyMTAyNDYyNzcw._V1_FMjpg_UX1000_.jpg', 'Seorang operator pintu tol pergi ke kampung leluhurnya dengan harapan mendapatkan harta warisan, hingga akhirnya ia menemukan fakta yang meresahkan tentang masa lalunya.', '2019-10-17', '17+', 9),
(141, 'The Matrix Resurrections', '3', 'https://m.media-amazon.com/images/M/MV5BNmI2ODhlYjYtMzhlYi00NzQ2LTk1Y2YtMDI5ZjRhNTQ2Y2ZiXkEyXkFqcGdeQXVyODc0OTEyNDU@._V1_.jpg', 'Kisah Neo berlanjut, perjuangan kali ini akan lebih sulit dari sebelumnya. Perang antara dua dunia kembali lagi terjadi. Diganggu oleh kenangan aneh, kehidupan Neo berubah secara tak terduga ketika dia menemukan dirinya kembali kedalam Matrix.', '2021-12-22', '17+', 8),
(142, 'Venom: Let There Be Carnage', '3', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/1MJNcPZy46hIy2CmSqOeru0yr5C.jpg', 'Venom kembali beraksi ketika seorang pembunuh berantai, Cletus Kasady bertransformasi menjadi sosok jahat Carnage.', '2021-11-17', '13+', 8),
(143, 'The Suicide Squad', '3', 'https://www.themoviedb.org/t/p/w500/kb4s0ML0iVZlG6wAKbbs9NAm6X.jpg', 'Penjahat super Harley Quinn, Bloodsport, Peacemaker, dan sekumpulan penjahat brutal dari penjara Belle Reve bergabung dengan Task Force X mereka ditugaskan secara rahasia di pulau Corto Maltese yang terpencil dan dipenuhi musuh.', '2021-09-16','17+', 4),
(144, 'Black Widow', '7', 'https://m.media-amazon.com/images/M/MV5BNjRmNDI5MjMtMmFhZi00YzcwLWI4ZGItMGI2MjI0N2Q3YmIwXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg', 'Natasha Romanoff alias Black Widow harus menghadapi sisi gelap hidupnya saat sebuah konspirasi berbahaya dikaitkan dengan masa lalunya. Dikejar oleh sesuatu yang tidak akan berhenti sampai berhasil menghancurkan hidupnya, Natasha harus kembali pada kenyataan bahwa ia adalah seorang mata-mata dan hubungan keluarganya yang hancur sebelum ia bergabung bersama Avengers.', '2021-07-09', '13+', 8),
(145, 'Top Gun: Maverick', '7', 'https://cinemags.org/wp-content/uploads/2019/12/topgunmaverickposter.jpg', 'Lebih dari 30 tahun mengabdi sebagai salah satu penerbang Angkatan Laut terbaik, Pete “Maverick” Mitchell berada dalam posisi dambaannya, melakukan aksi-aksi mendobrak sebagai pilot uji nan pemberani, dan menampik setiap kesempatan naik pangkat karena akan membuatnya tak bisa menerbangkan pesawatnya.', '2022-05-24', '17', 8),
(146, 'Fast & Furious 9', '3', 'https://i.pinimg.com/564x/b4/e6/bf/b4e6bf979b5919dde0ba2a81f30dfafb.jpg', 'Dom Toretto (Vin Diesel) menjalani kehidupan yang tenang dengan Letty dan putranya, Brian kecil, tetapi mereka tahu bahwa bahaya selalu mengintai. Kali ini, ancaman itu akan memaksa Dom untuk menghadapi kesalahan dari masa lalunya jika dia ingin menyelamatkan orang yang paling dia cintai. Krunya bergabung bersama untuk menghentikan sesuatu yang dapat menghancurkan dunia. serangan dipimpin oleh pembunuh paling terampil dan pengemudi yang sangat handal dan juga merupakan saudara laki-laki Dom yang ditinggalkan, Jakob (John Cena)', '2021-06-16', '13+', 7),
(147, 'Mortal Kombat', '7', 'https://statics.indozone.news/local/60519c45d6d2d.jpg', 'Petarung MMA Cole Young, yang terbiasa menerima pukulan demi uang, tidak menyadari warisannya-atau mengapa Kaisar Dunia Luar Shang Tsung telah mengirim prajurit terbaiknya, Sub-Zero, seorang Cryomancer dunia lain, untuk memburu Cole. Khawatir akan keselamatan keluarganya, Cole pergi mencari Sonya Blade ke arah Jax, seorang Mayor Pasukan Khusus yang memiliki tanda naga aneh yang sama dengan Cole saat lahir.', '2021-04-14', '21+', 8),
(148, 'Godzilla vs. Kong', '3', 'https://m.media-amazon.com/images/M/MV5BYjFhOGFiNGQtZTBjZS00NTUzLTk4YTQtOTkxMjEyZTI5ZTk0XkEyXkFqcGdeQXVyMTA3MDk2NDg2._V1_.jpg', 'Sebuah pertarungan epic dalam sinematik Monsterverse antara Godzilla dan Kong.Pertarungan Godzilla vs. Kong membuat umat manusia harus bertahan dengan berbagai cara. Salah satunya adalah memusnahkan kedua raksasa tersebut.Siapa yang akan menang?', '2021-03-24', '13+', 4),
(149, 'Train To Busan Presents Peninsula', '4', 'https://m.media-amazon.com/images/M/MV5BOWFmNmVjOGYtNzlkMS00N2U2LWI4NDYtNzRjNTQxODZlNTYyXkEyXkFqcGdeQXVyNDg4NjY5OTQ@._V1_.jpg', 'Ketika wabah zombie melanda, Jung-seok (GANG Dong-won) nyaris tidak lolos dari Korea Selatan hidup-hidup. Ketika hidup dalam keputusasaan di Hong Kong, ia menerima tawaran yang menarik untuk kembali ke semenanjung yang dikarantina. Misinya adalah untuk mengambil truk yang ditinggalkan di tengah Seoul dalam batas waktu dan melarikan diri dari semenanjung dengan diam-diam.', '2020-10-16', '13+', 4),
(150, 'Alive', '2', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/zb06eXz3Pg5JzytPnMFb3cIDV7B.jpg', 'Saat virus mengerikan merajalela di kota, seorang pria mengunci diri di apartemennya, tak bisa mencari bantuan secara digital dan terdesak untuk menemukan jalan keluar.', '2020-06-24', '17+', 8),
(151, 'Wonder Woman 1984', '3', 'https://m.media-amazon.com/images/M/MV5BYWFjNGQxZjItOTgxNy00NjhkLWFkZGQtOWVjNzJlYWNhM2NmXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg', 'Berlatar setting tahun 1980-an, petualangan Wonder Woman selanjutnya adalah menghadapi dua musuh baru: Max Lord dan The Cheetah.', '2020-12-16', '13 +', 7),
(152, '6 Underground', '7', 'https://m.media-amazon.com/images/M/MV5BNzE2ZjQxNjEtNmI2ZS00ZmU0LTg4M2YtYzVhYmRiYWU0YzI1XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg', 'Setelah memalsukan kematiannya, seorang miliarder teknologi merekrut tim operasi internasional untuk misi yang berani dan berdarah untuk menjatuhkan seorang diktator brutal.', '2019-12-10', '17+', 6),
(153, 'Angel Has Fallen', '2', 'https://m.media-amazon.com/images/M/MV5BYmRmMWZhZGItYzA4MC00ZDYyLWE0OTMtYmM0MWRiN2Q4NGU2XkEyXkFqcGdeQXVyMjMxOTE0ODA@._V1_FMjpg_UX1000_.jpg', 'Pasca percobaan pembunuhan Presiden AS. Agen rahasia Mike Banning (Gerard Butler) kini menjadi tersangka utama. Tidak terima, Mike kabur dan berusaha mengungkap pihak yang telah menjebaknya.', '2019-08-21', '13+', 8),
(154, 'Captain Marvel', '3', 'https://m.media-amazon.com/images/M/MV5BZjlhZWQ3N2ItNGI3Ny00MWVhLTg5NDctOTI1OGEyZWI4MjM3XkEyXkFqcGdeQXVyMTgxOTIzNzk@._V1_FMjpg_UX1000_.jpg', 'Kisah ini mengikuti Carol Danvers saat ia menjadi salah satu pahlawan paling kuat di alam semesta ketika Bumi terperangkap di tengah perang galaksi antara dua ras alien. Bertempat di tahun 1990-an, Kapten Marvel adalah petualangan yang sepenuhnya baru dari periode yang sebelumnya tidak terlihat dalam sejarah Marvel Cinematic Universe.', '2019-03-08', '13+', 8),
(155, 'Fast & Furious: Hobbs & Shaw', '7', 'http://assets.kompasiana.com/items/album/2019/08/01/fast-furious-hobbs-shaw-poster-5d423811097f366b543fd895.jpg', 'bercerita Luke Hobbs terpaksa membentuk aliansi yang mustahil dengan Deckard Shaw. Keduanya terpaksa bersatu membantu Hattie Shaw untuk memburu senjata virus berbahaya dan Brixton. Brixton adalah penjahat jenis baru yang berhasil mengubah dirinya menjadi manusia super. Keberadaanya menjadi ancaman bagi umat manusia.', '2019-07-31', '13+', 8),
(156, 'Men in Black: International', '6', 'https://m.media-amazon.com/images/M/MV5BZTBmZGNiNGEtZmIxYy00NDgxLWE4MGItYzkwYjg2YzQ1Nzk1XkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_.jpg', 'Men in Black selalu melindungi Bumi dari penjahat alam semesta. Dalam petualangan baru ini, mereka harus mengatasi ancaman terbesar mereka hingga saat ini: mata - mata yang ada dalam organisasi Men in Black.', '2019-06-19', '13+', 8),
(157, 'Hotel Transylvania: Transformania', '4', 'https://m.media-amazon.com/images/M/MV5BYWJmNzRiMWEtNzk3Ni00OGU5LThlMDctYmJhMTA1YzEzNjY4XkEyXkFqcGdeQXVyMTM0NTUzNDIy._V1_.jpg', 'Ketika penemuan misterius Van Helsing, "Monsterfication Ray," menjadi kacau, Drac dan teman-teman monsternya semuanya berubah menjadi manusia, dan Johnny menjadi monster. Dalam tubuh baru mereka yang tidak serasi, Drac dan Johnny harus bekerja sama dan berlomba melintasi dunia untuk menemukan obat sebelum terlambat, dan sebelum mereka saling membuat gila.', '2022-02-25', 'SU', 6),
(158, 'One Piece: Stampede', '4', 'https://m.media-amazon.com/images/M/MV5BM2MxY2QwYTAtMDM1My00MTc0LWEwZjktMDdjODY2NWJiNDg2XkEyXkFqcGdeQXVyODY3ODQ2MTk@._V1_.jpg', 'mereka diundang ke acara besar yang dikenal sebagai Pirates expo! Semua bajak laut terhebat berkumpul di pameran bajak laut,tiba-tiba angkatan laut ikut campur dalam kegiatan tersebut, Sebenarnya ada konspirasi apakah dibalik acara tersebut?', '2019-09-18', 'SU', 8),
(159, 'X-Men: Dark Phoenix', '3', 'https://m.media-amazon.com/images/M/MV5BOWFjODY0OWItMjk4OS00OTIwLWJiZDctY2FkMzlhYTZmZTllXkEyXkFqcGdeQXVyMTAzMDM4MjM0._V1_.jpg', 'Film X Men Dark Pheonix ini meneceritakan asal usul Jean Grey, wanita mutan terkuat yang mampu menggerakan semua benda. Tentang bagaimana Jean Gray mulai mengembangkan kekuatan luar biasa yang merusak dan mengubahnya menjadi Dark Phoenix. Sekarang X-Men harus memutuskan apakah kehidupan anggota tim lebih berharga daripada semua orang yang hidup di dunia.', '2019-06-08', '13+', 8),
(160, 'Jumanji: The Next Level', '6', 'https://m.media-amazon.com/images/M/MV5BOTVjMmFiMDUtOWQ4My00YzhmLWE3MzEtODM1NDFjMWEwZTRkXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg', 'Dalam Jumanji: The Next Level, keempat sahabat kembali lagi, tetapi permainannya telah berubah. Saat memutuskan masuk lagi ke Jumanji untuk menyelamatkan salah satu dari mereka, mereka menemukan segalanya tak seperti yang diduga. Para pemain harus melaju ke wilayah-wilayah tersembunyi dan belum dijamah, dari gurun nan gersang ke pegunungan bersalju, demi meloloskan diri dari permainan paling berbahaya di dunia.', '2019-12-04', '13+', 7),
(161, 'Shazam!', '3', 'https://i.pinimg.com/originals/80/b9/d7/80b9d7b39f7a8155fa0d0a2a74a61e32.jpg', 'Setelah invasi Steppenwolf, Billy Batson seorang remaja berusia 14 tahun yang bermasalah bersiap-siap untuk pindah ke rumah orang tua asuhnya yang baru. Ia yatim piatu yang tinggal di Philadelphia, dimana suatu hari ia masuk ke dimensi lain dan bertemu penyihir Shazam yang memberinya kekuatan.', '2019-04-05', '13+', 6),
(162, 'John Wick: Chapter 3 - Parabellum', '3', 'https://m.media-amazon.com/images/M/MV5BZjRkZWI5MDYtNWViNC00OWQ5LThkYzktZDU2NTQ4Zjk4NDMwXkEyXkFqcGdeQXVyNDIzMTQwODY@._V1_.jpg', 'Super-pembunuh John Wick kembali dengan label harga $ 14 juta di kepalanya dan sepasukan pembunuh pemburu hadiah di jejaknya. Setelah membunuh anggota guild pembunuh bayang-bayang internasional, High Table, John Wick dikucilkan, tetapi pria dan wanita hit paling kejam di dunia menunggu setiap gilirannya.', '2019-05-17', '17+', 8),
(163, 'Godzilla II: King of the Monsters', '3', 'https://m.media-amazon.com/images/M/MV5BOTVjYmY2YzAtYWRiOC00MzZlLThhYjItMDRmYTJiNmVkNzllXkEyXkFqcGdeQXVyODc0OTEyNDU@._V1_.jpg', 'Kisah baru ini mengikuti upaya heroik agensi kripto zoologi Monarch ketika anggotanya berhadapan dengan monster seukuran dewa, termasuk Godzilla yang perkasa, yang harus berhadapan dengan Mothra, Rodan, dan musuh bebuyutannya, si kepala tiga King Ghidorah. Ketika super spesies purba iniyang sebelumnya hanya dianggap mitosbangkit kembali, mereka semua bersaing untuk supremasi, membuat keberadaan manusia tergantung dalam keseimbangan.', '2019-05-29', '13+', 7),
(164, 'Pengabdi Setan', '5', 'https://m.media-amazon.com/images/M/MV5BNjFhZGM0NGEtZDc1OS00ZGM2LWFkZTYtY2NiYTdlZDk2OTkyXkEyXkFqcGdeQXVyOTAwMzEwNjM@._V1_.jpg', 'Setelah sakit aneh selama 3 tahun, Ibu akhirnya meninggal dunia. Bapak lalu memutuskan untuk kerja di luar kota meninggalkan anak-anak. Tak lama kemudian, anak-anak merasa bahwa Ibu kembali berada di rumah. Situasi semakin menyeramkan ketika mereka mengetahui bahwa Ibu datang lagi tidak sekedar untuk menjenguk, tapi untuk menjemput mereka.', '2017-09-28', '17+', 9),
(165, 'The Ice Age Adventures of Buck Wild', '4', 'https://m.media-amazon.com/images/M/MV5BNDJmMzQyMzAtMzMxMy00NTI3LTgzOGMtZDU3Yzc4MjRjNzkwXkEyXkFqcGdeQXVyMTA1OTcyNDQ4._V1_FMjpg_UX1000_.jpg', 'Musang bermata satu yang tak kenal takut, Buck, bekerja sama dengan saudara possum yang nakal, Crash & Eddie, saat mereka memulai petualangan baru ke rumah Buck: Dunia Dinosaurus.', '2022-01-28', 'SU', 7),
(166, 'Sebelum Iblis Menjemput', '5', 'https://m.media-amazon.com/images/M/MV5BMTI4NWFhNzItYzEwNS00ODNmLTg3NWUtMjY1ZTAzZWQ0NjBhXkEyXkFqcGdeQXVyNzY4NDQzNTg@._V1_.jpg', 'Alfie dan Nara harus kembali bertempur dengan pasukan iblis. Alih-alih terbebas dari teror, Alfie dan Nara diculik oleh sekumpulan orang tak dikenal. Mereka berpendapat bahwa Alfie merupakan sosok “tangguh” dan hanya dirinyalah yang dapat menjalankan ritual agar mereka terbebas dari teror sosok iblis Ayub', '2018-08-09', '17+', 10),
(167, 'My Stupid Boss', '6', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/3V16r41x68R6uVHpm9TIga5593T.jpg', 'Cerita tentang hubungan kerja antara Boss yang absurd dengan karyawannya. “Bossman” (Reza Rahadian) adalah orang Indonesia yang memiliki perusahaan di Kuala Lumpur.', '2016-05-19', '13+', 9),
(168, 'Cek Toko Sebelah', '6', 'https://m.media-amazon.com/images/M/MV5BMDFlZDhjMDctODI4Yy00NjZkLWJkNWYtNGExNWVkZDA1MGNiL2ltYWdlXkEyXkFqcGdeQXVyMzUwMTk4OTI@._V1_FMjpg_UX1000_.jpg', 'Erwin menikmati hidupnya dengan karir gemilang di usia muda, dan kekasih cantik yang tak kalah sukses, Natalie. Tapi semua jadi pelik saat Koh Afuk yang kesehatannya makin memburuk, ingin mewariskan toko sembakonya kepada Erwin, anak kesayangannya.', '2016-12-20', '13+', 8),
(169, 'Koala Kumal ', '6', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/1OgZEiPTCaDPz3jfOvyDBEJBFYy.jpg', 'Dika (Raditya Dika) adalah seorang cowok yang baru saja batal menikah karena pacarnya, Andrea (Acha Septriasa) selingkuh darinya dengan cowok bernama James (Nino Fernandez). Patah hatinya membuat Dika kesulitan menulis bab terakhir dari bukunya. Suatu hari, Dika bertemu dengan cewek bernama Trisna (Sheryl Sheinafia), cewek yang unik yang membuat sudut pandang Dika terhadap dunia menjadi berbeda.', '2016-07-06', '13+', 8),
(170, 'Reuni Z', '6', 'https://m.media-amazon.com/images/M/MV5BNjFkYWRiMWEtY2EwMS00MjVhLWFhNjMtYWMwYTFhNmNhMWNlXkEyXkFqcGdeQXVyNzQyODU3NzU@._V1_FMjpg_UX1000_.jpg', 'Seorang aktor B-list terhubung kembali dengan teman band SMA-nya di sebuah reuni yang segera terurai ketika sekelompok petugas berubah menjadi zombie.', '2018-04-12', '13+', 4),
(171, 'The Last Dance', '1', 'https://m.media-amazon.com/images/M/MV5BY2U1ZTU4OWItNGU2MC00MTg1LTk4NzUtYTk3ODhjYjI0MzlmXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg', 'The Last Dance adalah miniseri dokumenter olahraga Amerika tahun 2020 yang diproduksi bersama oleh ESPN Films dan Netflix. Disutradarai oleh Jason Hehir, serial ini berkisah tentang karir Michael Jordan, dengan fokus khusus pada musim terakhirnya bersama Chicago Bulls.', '2020-04-19', 'SU', 9),
(172, 'Squid Game', '2', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/yACIAqAkSLkX4coHafpyLWAtQjw.jpg', 'Ratusan pemain yang pailit menerima undangan aneh untuk bertanding dalam permainan anak-anak—dengan taruhan besar. Namun, hadiah menggiurkan menanti sang juara.', '2021-09-17', '17+', 10),
(173, 'Jurassic World: Fallen Kingdom', '3', 'https://m.media-amazon.com/images/M/MV5BNzIxMjYwNDEwN15BMl5BanBnXkFtZTgwMzk5MDI3NTM@._V1_FMjpg_UX1000_.jpg', 'Setelah Isla Nublar porak-poranda akibat letusan gunung berapi, spesies dinosaurus yang tersisa dibawa ke perkebunan Lockwood yang besar, di Amerika. Di tempat tersebut, Owen dan Claire menyadari bahwa spesies dinosaurus malah dilelang dan tidak dilestarikan. Seekor dinosaurus hibrida yang sangat berbahaya dan dikenal dengan nama Indoraptor, kabur dan mulai meneror penduduk di sekitar perkebunan.', '2018-06-06', '13+', 6),
(174, 'Alice in Borderland', '2', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/i0i7kGDrArtM1sCd8niZDC7iboV.jpg', 'Seorang gamer tanpa tujuan dan dua temannya terdampar di Tokyo paralel. Di sana, mereka dipaksa bertanding dalam serangkaian permainan sadis agar bisa bertahan hidup.', '2020-12-10', '17+', 7),
(175, 'All of Us Are Dead', '2', 'https://m.media-amazon.com/images/M/MV5BOTY1ZGM2YzQtMTBjZC00NjE2LWJlNzUtYjA0YjYxNzBjMmRjXkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_FMjpg_UX1000_.jpg', 'Sebuah sekolah menengah menjadi titik nol untuk wabah virus zombie. Siswa yang terjebak harus berjuang keluar atau berubah menjadi salah satu yang terinfeksi rabies.', '2022-01-28', '17+', 8),
(176, 'Hellbound', '2', 'https://m.media-amazon.com/images/M/MV5BNzU1ODk0ZWUtMzdkYS00YmI2LWI1NjItOTg0NjQxNGY5MmNlXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_.jpg', 'Hellbound bercerita tentang sekelompok monster yang memburu orang-orang yang dianggap berdosa dan mengirim mereka ke neraka. Sang pendosa akan diberitahu tanggal dan waktu kematian mereka sebelum akhirnya dikejar oleh monster.', '2021-11-19', '21+', 7),
(177, 'Running Man', '2', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/15SMnscZqd7HZ0bzruatOcKUlOV.jpg', 'Hari-hari ini, berbagai hiburan secara bertahap menghilang. Dalam program ini, banyak bintang dan anggota bermain game dan misi bersama. Hal ini ditandai dengan berkeliling beberapa tempat. Secara khusus, program ini hanya berfokus pada tawa di antara banyak elemen hiburan yang menyenangkan.', '2010-07-11', 'SU', 8),
(178, 'The Doll', '5', 'https://m.media-amazon.com/images/M/MV5BNzU4MzM1ZjItNmE2Yi00NTRjLWFhNjMtZjdlZGRmZjA4NjAxXkEyXkFqcGdeQXVyMzYzOTYxNzM@._V1_FMjpg_UX1000_.jpg', 'Sepasang suami istri, Anya dan Daniel baru saja pindah ke sebuah rumah di Bandung dan siap menjalani kehidupan baru mereka. Tanpa sengaja, Daniel membawa pulang sebuah boneka dari lokasi proyek tempat ia bekerja yang ada di Jalan Siliwangi. Boneka tersebut ada di atas pohon yang kemudian Daniel tebang untuk keperluan proyek real estatenya. Anya yang pembuat boneka dengan senang hati meletakkan boneka itu di rumah mereka. Tapi Niken, tetangganya kaget ketika melihat boneka itu.', '2016-10-27', '17+', 7),
(179, 'Captain America: Civil War', '3', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/8xA9XQ6KfvXFKcNLNRWSPT39Gaz.jpg', 'Menyusul peristiwa Age of Ultron, pemerintah kolektif dunia mengeluarkan tindakan yang dirancang untuk mengatur semua aktivitas manusia super. Ini mempolarisasi pendapat di antara Avengers, menyebabkan dua faksi memihak Iron Man atau Captain America, yang menyebabkan pertempuran epik antara mantan sekutu.', '2016-04-27', '13+', 8),
(180, 'The Nun', '5', 'https://m.media-amazon.com/images/M/MV5BNjZlOGVhZDctODU2Yi00NzcyLWFlNmItZGQ2ZDc2NTIwNGMyXkEyXkFqcGdeQXVyNzkwMTYyMTI@._V1_.jpg', 'Ketika seorang biarawati muda di biara terpencil Rumania mengorbankan hidupnya sendiri, seorang pendeta dengan masa lalu yang kelam dan seorang calon biarawati dikirim oleh Vatikan untuk menyelidiki peristiwa ini. Bersama-sama mereka membuka rahasia rahasia yang tidak terduga. Mempertaruhkan tidak hanya hidup mereka tetapi iman mereka dan jiwa mereka, keduanya menghadapi kekuatan jahat dalam bentuk iblis biarawati yang pertama kali meneror para penonton di The Conjuring 2.', '2018-09-05', '17+', 8);


ALTER TABLE `film`
  ADD PRIMARY KEY (`id`);


ALTER TABLE `film`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=181;
COMMIT;


